name: sync gee repo

on:
  # Allows you to run this workflow manually from the Actions tab
  # Generate GIT_COOKIE_VALUE from https://earthengine.googlesource.com/new-password
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: grant access
        env:
          GIT_COOKIE_VALUE: ${{ secrets.GIT_COOKIE_VALUE }}
        run: |
          touch ~/.gitcookies
          chmod 0600 ~/.gitcookies
          echo earthengine.googlesource.com,FALSE,/,TRUE,2147483647,o,${GIT_COOKIE_VALUE} | tr  , \\t >>~/.gitcookies
          git config --global http.postBuffer 157286400

      - name: config git
        run: |
          git config --global http.cookiefile ~/.gitcookies
          git config --global user.email "githubActionAutoMerge@no-one.com"
          git config --global user.name "githubActionAutoMerge"
          git config --global pull.rebase false

      - name: sync gee git repo
        env:
          GEE_REPO: ${{ secrets.GEE_REPO }}
        run: |
          # Pull the latest changes from the external GEE_REPO
          git pull https://earthengine.googlesource.com/${GEE_REPO}.git master --allow-unrelated-histories || bash -c "git checkout --theirs . ; git add -u ; git commit -m 'autoMerge'"

          # Push the commit to the main GitHub repository
          git push
